version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=Guest
      - RABBITMQ_DEFAULT_PASS=Guest
